# Generated by Django 4.2.4 on 2023-09-21 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 9, 21, 22, 53, 19, 851610, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 22, 53, 19, 851610, tzinfo=datetime.timezone.utc)),
        ),
    ]
